FROM maven:3-jdk-8-alpine AS MAVEN_BUILD

COPY pom.xml /build/
COPY src /build/src/

WORKDIR /build/

RUN mvn package
#RUN mvn spring-boot:run

FROM openjdk:8-jre-alpine
RUN apk add --no-cache bash
RUN mkdir -p /app
WORKDIR /app
COPY --from=MAVEN_BUILD /build/target/docker-vrplayer-backend.jar /app/

ENTRYPOINT ["java", "-jar", "docker-vrplayer-backend.jar"]

# docker image build -t docker-backend-run -f Dockerfile-back-run .
# docker container run -p 8080:8080 docker-vrplayer-backend