FROM maven:3-jdk-8-alpine AS MAVEN_BUILD

COPY pom.xml /build/
COPY src /build/src/

WORKDIR /build/

RUN mvn package

# docker image build -f Dockerfile-back-build  .
# docker create docker-backend
# docker cp docker-backend:/build/target/docker-vrplayer-backend.jar ./
